services:
  db:
    image: mariadb:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog
      MYSQL_USER: adintel
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db: